services:
  web:
    userns_mode: keep-id
    volumes:
      - .:/app:z
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/coffeedb
      - PYTHONPATH=/app
      - FLASK_APP=src.app
    command: python -m flask run --host=0.0.0.0 --port=5000 --debug

  seed:
    userns_mode: keep-id
    volumes:
      - .:/app:z
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/coffeedb
      - PYTHONPATH=/app
      - FLASK_APP=src.app
