apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: coffee-finder
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: coffee-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:18
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: env-config
              mountPath: /docker-entrypoint-initdb.d/.env
              subPath: .env
          envFrom:
            - configMapRef:
                name: coffee-env-config
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "user", "-d", "coffeedb"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "user", "-d", "coffeedb"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
        - name: env-config
          configMap:
            name: coffee-env-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: coffee-finder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
